### PR TITLE
Allow empty models to be created

### LINKED ISSUE #238: Ipopt fails to load an empty model
```Julia
model = Ipopt.Optimizer()
MOI.optimize!(model)

julia> MOI.optimize!(model)
ERROR: IPOPT: Failed to construct problem.
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] createProblem(::Int64, ::Array{Float64,1}, ::Array{Float64,1}, ::Int64, ::Array{Float64,1}, ::Array{Float64,1}, ::Int64, ::Int64, ::Ipopt.var"#eval_f_cb#46"{Ipopt.Optimizer}, ::Ipopt.var"#eval_g_cb#48"{Ipopt.Optimizer}, ::Ipopt.var"#eval_grad_f_cb#47"{Ipopt.Optimizer}, ::Ipopt.var"#eval_jac_g_cb#49"{Ipopt.Optimizer,Array{Tuple{Int64,Int64},1}}, ::Ipopt.var"#eval_h_cb#50"{Ipopt.Optimizer,Array{Tuple{Int64,Int64},1}}) at /home/parallels/.julia/packages/Ipopt/bYzBL/src/Ipopt.jl:250
 [3] optimize!(::Ipopt.Optimizer) at /home/parallels/.julia/packages/Ipopt/bYzBL/src/MOI_wrapper.jl:1104
 [4] top-level scope at REPL[3]:1
```

### PR DESCRIPTION
**Pull request by odow**
Closes #238

### CODE REVIEW

**Comment by frapac** [comment]
I am not sure to understand why this is useful. If the user does not provide any variable, I would expect the wrapper to return an error instead of adding silently a dummy variable.

**Comment by mlubin** [comment]
I'd vote for catching this and reporting a more useful error than Ipopt's internal error.

**Comment by odow** [comment]
@frapac is this better?

**Comment by frapac** [comment]
Looks good to me! Thanks for adding this error, I think it's better to state things explicitly.

**Review by blegat — APPROVED** [review]

**Pull request merged**
