### PR TITLE
Test Ipopt.jl on FreeBSD and Apple M1

### PR DESCRIPTION
**Pull request by amontoison**
Oscar, is it possible to activate Cirrus CI?

### CODE REVIEW

**Comment by odow** [comment]
Where and how do I do this?

**Comment by amontoison** [comment]
You need to activate CirrusCI in the settings of the `jump-dev` organization.

**Comment by odow** [comment]
I've installed for Ipopt

image

**Comment by odow** [comment]
Closing in favor of https://github.com/jump-dev/Ipopt.jl/pull/371

**Comment by odow** [comment]
Ah you pushed just as I opened a new PR :smile:

**Comment by odow** [comment]
I wondered if the first addition needed to come from our remote, rather than a fork

**Comment by amontoison** [comment]
I just needed to rebase. :smiley: 
I will open a last PR to explain how to set the SPRAL linear solver that is available with the last  `Ipopt_jll` and we should be good.

**Pull request closed without merging**
