### PR TITLE
Precompile some functions

### PR DESCRIPTION
**Pull request by joehuchette**

### CODE REVIEW

**Comment by tkelman** [comment]
:+1:

Did you just follow the stock SnoopCompile readme instructions?

**Comment by joehuchette** [comment]
Essentially, I ran the nonlinear benchmarks from https://github.com/mlubin/JuMPSupplement and went with that.

**Comment by tkelman** [comment]
Should any of the `Int64`s actually be `Int` for the sake of 32 bit? Would that cause method errors or just not give the right speedup?

**Comment by joehuchette** [comment]
Using ``Int`` is probably the right thing to do, but I'm pretty sure it doesn't cause any harm, just precompile an extraneous method.

**Comment by odow** [comment]
Closing as stale. We should revisit precompile statements wholesale across JuMP-dev.

**Pull request closed without merging**
