### PR TITLE
Fix support for MOI.Name

### LINKED ISSUE #317: add `MathOptInterface.Name()` attribute
When using Ipopt and ParametricOptInterface in direct mode this error happens: 

```Julia
julia> model = direct_model(POI.Optimizer(Ipopt.Optimizer()))
Error showing value of type Model:
ERROR: MathOptInterface.GetAttributeNotAllowed{MathOptInterface.Name}: Getting attribute MathOptInterface.Name() cannot be performed: Ipopt.Optimizer does not support getting the attribute MathOptInterface.Name(). You may want to use a `CachingOptimizer` in `AUTOMATIC` mode or you may need to call `reset_optimizer` before doing this operation if the `CachingOptimizer` is in `MANUAL` mode.
```

### PR DESCRIPTION
**Pull request by odow**
Closes #317

### CODE REVIEW

**Comment by blegat** [comment]
I don't think Ipopt should implement this

**Comment by odow** [comment]
It's optional, but not unreasonable. We support other attributes that Ipopt itself doesn't (like `SolveTimeSec`).

**Comment by blegat** [comment]
`SolveTimeSec` makes sense as we have no fallback for it and it's reasonable for users to want that.
However, I don't think we should complicate all solver wrappers with getter for the model if the solver does not support that.
We should make JuMP's printing use `try`-`catch` to be robust to that instead.

**Comment by odow** [comment]
> We should make JuMP's printing use

Yeah, that was https://github.com/jump-dev/JuMP.jl/pull/3017. But I added it here in addition because it was trivial. Agree that not every solver has to implement.

**Pull request merged**
